#!/gpfs01/software/imaging/miniconda3/envs/xnat/bin/python
"""
Script to create assessor XML from the output of hte BRC pipeline
"""
import sys
import os
import shutil
import datetime

import pandas as pd

__version__ = "0.0.1"

XML_HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<PipelineData xmlns="http://github.com/spmic-uon/xnat-hpc" xmlns:xnat="http://nrg.wustl.edu/xnat" xsi:schemaLocation="http://github.com/spmic-uon/xnat-hpc schema.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <xnat:label>%s</xnat:label>
  <pipelineVersion>%s</pipelineVersion>
  <pipelineName>%s</pipelineName>
"""

XML_FOOTER = """</PipelineData>"""

def get_label(cmd):
    now = datetime.datetime.now()
    timestamp = now.strftime("%Y%m%d_%H%M%S")
    return f"{cmd}_{timestamp}"

def create_assessor_xml(assessordir):
    json_files = []
    label = get_label("BRC_PIPELINE")
    xml = XML_HEADER % (label, __version__, "BRC Pipeline")
    xml += "  <xnat:date>%s</xnat:date>\n" % datetime.datetime.today().strftime('%Y-%m-%d')
    xml += XML_FOOTER

    with open(os.path.join(assessordir, "brc.xml"), "w") as f:
        f.write(xml)

def copy_file(srcdir, path, destdir):
    srcfile = os.path.join(srcdir, path)
    if os.path.exists(srcfile):
        shutil.copy(srcfile, destdir)

def get_subjdir(brcdir):
    subjdirs = [os.path.join(brcdir, d) for d in os.listdir(brcdir)]
    subjdirs = [d for d in subjdirs if os.path.isdir(d) and not d.endswith("/idps")]
    if len(subjdirs) == 0:
        sys.stderr.write("WARNING: No subject directories found, no data will be uploaded")
        return
    elif len(subjdirs) > 1:
        sys.stderr.write("WARNING: Multiple subject directories found: %s - using first" % subjdirs)
    return subjdirs[0]

def create_resource_files(brcdir, assessordir):
    subjdir = get_subjdir(brcdir)
    if subjdir:
        defaced_dir = os.path.join(assessordir, "brc", "DEFACED")
        os.makedirs(defaced_dir, exist_ok=True)
        copy_file(subjdir, "raw/anatMRI/T2/T2_orig_defaced.nii.gz", defaced_dir)
        copy_file(subjdir, "raw/anatMRI/T1/T1_orig_defaced.nii.gz", defaced_dir)
        seg_dir = os.path.join(assessordir, "brc", "SEG")
        os.makedirs(seg_dir, exist_ok=True)
        copy_file(subjdir, "analysis/anatMRI/T1/processed/data/T1_unbiased.nii.gz", seg_dir)
        copy_file(subjdir, "analysis/anatMRI/T1/processed/data/T1_unbiased_brain.nii.gz", seg_dir)
        copy_file(subjdir, "analysis/anatMRI/T1/processed/seg/tissue/multi_chan/T1_pve_CSF.nii.gz", seg_dir)
        copy_file(subjdir, "analysis/anatMRI/T1/processed/seg/tissue/multi_chan/T1_pve_GM.nii.gz", seg_dir)
        copy_file(subjdir, "analysis/anatMRI/T1/processed/seg/tissue/multi_chan/T1_pve_WM.nii.gz", seg_dir)
        trans_dir = os.path.join(assessordir, "brc", "TRANS")
        os.makedirs(trans_dir, exist_ok=True)
        copy_file(subjdir, "analysis/anatMRI/T2/preproc/reg/T2_2_std_warp_field.nii.gz", trans_dir)
        copy_file(subjdir, "analysis/anatMRI/T2/preproc/reg/T2_2_std.mat", trans_dir)
        copy_file(subjdir, "analysis/anatMRI/T1/preproc/reg/T1_2_std_warp_field.nii.gz", trans_dir)
        copy_file(subjdir, "analysis/anatMRI/T1/preproc/reg/T1_2_std.mat", trans_dir)

def create_idp_resource(brcdir, assessordir):
    subjdir = get_subjdir(brcdir)
    if subjdir:
        idp_dir = os.path.join(assessordir, "brc", "IDPS")
        os.makedirs(idp_dir, exist_ok=True)

        idps_file = os.path.join(subjdir, "analysis/IDP_files/IDPs.txt")
        idp_names_file = os.path.join(os.environ["BRC_GLOBAL_DIR"], "config", "IDP_list.txt")
        idp_names = pd.read_csv(idp_names_file, sep="\s+", header=None)
        with open(idps_file, "r") as f:
            idps = f.read().split()

        with open(os.path.join(idp_dir, "IDPS.tsv"), "w") as f:
            f.write("SubjID\t" + "\t".join(idp_names[1]) + "\n")
            f.write("\t".join(idps) + "\n")

print("BRC pipeline - Create assessor: %s" % sys.argv)
workdir = sys.argv[1]
brcdir = os.path.join(workdir, "brc_out")
assessordir = os.path.join(workdir, "xnat-upload")
os.makedirs(assessordir, exist_ok=True)

create_assessor_xml(assessordir)
create_resource_files(brcdir, assessordir)
create_idp_resource(brcdir, assessordir)
