#!/bin/env /software/imaging/miniconda3/envs/xnat/bin/python
"""
Script to run the BRC pipeline from a BIDS dataset

Currently the structural pipeline only
"""
import os
import sys
import subprocess

import bids

__version__ = "0.0.1"

bidsdir = sys.argv[1]
outdir = sys.argv[2]
layout = bids.BIDSLayout(bidsdir)

for subject in layout.get_subjects():
    for session in layout.get_sessions():
        t1s = layout.get(subject=subject, session=session, extension='nii.gz', suffix='T1w', return_type='filename')
        if len(t1s) == 0:
            raise RuntimeError(f"Cannot run structural pipeline for subject {subject} session {session} - no T1w image found")
        if len(t1s) > 1:
            sys.stderr.write(f"WARNING: More than one T1w image found for subject {subject} session {session}: {t1s} - using first\n")
        t1 = t1s[0]

        t2s = layout.get(subject=subject, session=session, extension='nii.gz', suffix='T2w', return_type='filename')
        if len(t2s) == 0:
            t2s = [None]
        elif len(t2s) > 1:
            sys.stderr.write(f"WARNING: More than one T2w image found for subject {subject} session {session}: {t2s} - using first\n")
        t2 = t2s[0]

        cmd = ['struc_preproc.sh', '--input', t1, '--path', outdir, '--subject', f'{subject}_{session}']
        if t2:
            cmd += ['--t2', t2]
        sys.stderr.write(" ".join(cmd))
        stdout = subprocess.check_output(cmd)
        stdout = stdout.decode("UTF-8")
        sys.stderr.write(stdout)

        # IDP extraction
        subjfile = os.path.join(outdir, "subjs.txt")
        with open(subjfile, "w") as f:
            f.write(f'{subject}_{session}')
        idpdir = os.path.join(outdir, 'idps')
        cmd_idp = ['idp_extract.sh', '--in', subjfile, '--indir', outdir, '--outdir', idpdir]
        stdout = subprocess.check_output(cmd_idp)
        stdout = stdout.decode("UTF-8")
        sys.stderr.write(stdout)

