#!/bin/bash -x
#
# XNAT remote command to run FSL_DEFACE on structural
# scans within a session

HOST=$1
JSESSION=$2
PROJ=$3
SUB=$4
EXP=$5
ARGS=$6

# Create working directory
SCRIPTNAME=`basename "$0"`
WORKDIR=`mktemp -d -p $HOME/tmp $SCRIPTNAME_XXXXXX`

{
echo $@
echo "Working directory: $WORKDIR"

module load conda-img
source activate xnat

# Convert session ID into a user alias token for subsequent upload authentication
CREDENTIALS=`$HOME/code/generic/get_user_alias $HOST $JSESSION`
CREDENTIALS=($CREDENTIALS)
echo "Obtained user alias token - alias: ${CREDENTIALS[0]}"

# Get session scans into a temp dir in BIDS format as required for mriqc
BIDSDIR=$WORKDIR/bids
xnatc --xnat=$HOST --project=$PROJ --subject=$SUB --experiment=$EXP --user=${CREDENTIALS[0]} --password=${CREDENTIALS[1]} --download=$BIDSDIR --download-format=bids
BIDS_DATASETDIR=$BIDSDIR/*
echo "Downloaded BIDS data to: $BIDS_DATASETDIR"

# Run MRIQC as a batch job
MRIQC_OUTDIR=$WORKDIR/mriqc_out
JOB_ID=`sbatch --parsable $HOME/code/slurm/mriqc.sh $BIDS_DATASETDIR $MRIQC_OUTDIR`
echo "MRIQC job ID: $JOB_ID"

# Run dependent job to do upload
UPLOAD_JOB_ID=`sbatch --parsable --dependency=afterok:$JOB_ID $HOME/code/slurm/upload_mriqc.sh $HOST $PROJ $SUB $EXP mriqc $MRIQC_OUTDIR ${CREDENTIALS[0]} ${CREDENTIALS[1]}` 
echo "MRIQC upload job ID: $UPLOAD_JOB_ID"

} >$WORKDIR/out.log 2>$WORKDIR/err.log

