#!/gpfs01/software/imaging/miniconda3/envs/xnat/bin/python
import sys
import json
import requests

host, jsession, project, subject, exp = sys.argv[1:]

with open("test.out", "w") as out:
    out.write(f"Test command running for XNAT at {host} (session token: {jsession})\n")
    out.write(f"Project: {project}, subject {subject}, experiment {exp}\n")

    r = requests.get(f"{host}/data/services/tokens/issue", cookies={"JSESSIONID" : jsession})  
    if r.status_code != 200:
        out.write(r.text)
        out.write("\n")
        sys.exit(1)
    else:
        result = json.loads(r.text)
        out.write("User alias=%s\n" % result["alias"])
        out.write("secret=%s\n" % result["secret"])

