#!/bin/bash
#
# This is an XNAT pipeline script that runs a remote command on 
# the HPC
#
# It requires that /home/xnat/bin/ssh-init-tomcat.sh has been executed
# which starts ssh-agent, adds the authentication key and writes the config
# to the file /home/xnat/bin/ssh-agent-tomcat-env
#
# Usage: run_hpc_ssh <XNAT host URL> <Project ID> <Subject ID> <Experiment ID> <Command to run>
# 
XNAT_SSH_KEY=/data/xnat/ssh/id_rsa_hpc
XNAT_BIN_DIR=/data/xnat/bin
XNAT_HPC_USER=service_hpc_xnat
HPC_LOGIN_NODE=login001.augusta.nottingham.ac.uk

# This is required because XNAT sometimes likes to run the pipeline script with
# --version as an argument and we don't want that getting sent to the HPC
if [ $1 = "--version" ]; then
  echo "0.0.1"
  exit 0
fi

echo "run_hpc_ssh.sh"
echo $@
. ${XNAT_BIN_DIR}/bin/ssh-agent-tomcat-env
HOST=$1
JSESSION=$2
PROJ=$3
SUBJ=$4
EXP=$5
CMD=$6
ARGS=$7
ssh -t -i ${XNAT_SSH_KEY} ${XNAT_HPC_USER}@${HPC_LOGIN_NODE} << EOF
./run.sh "$CMD" "$HOST" "$JSESSION" "$PROJ" "$SUBJ" "$EXP" "$ARGS"
EOF

